-- DESATIVA CONSTRAINTS TEMPORARIAMENTE (opcional, caso queira prevenir problemas)
ALTER TABLE TB_PALPITES NOCHECK CONSTRAINT ALL;
ALTER TABLE TB_PARTIDA_ESTAITSTICA_ESPERADAS NOCHECK CONSTRAINT ALL;
ALTER TABLE TB_ESTATISTICA_ESPERADAS NOCHECK CONSTRAINT ALL;

-- DROP TABLES EM ORDEM CORRETA (filhos antes dos pais)
DROP TABLE IF EXISTS TB_PARTIDA_ESTAITSTICA_ESPERADAS;
DROP TABLE IF EXISTS TB_PALPITES;
DROP TABLE IF EXISTS TB_ESTATISTICA_ESPERADAS;
DROP TABLE IF EXISTS TB_PARTIDAS;
DROP TABLE IF EXISTS TB_ESTATISTICA_TIME;
DROP TABLE IF EXISTS TB_ESTATISTICA_BASEMODEL;
DROP TABLE IF EXISTS TB_ESTATISTICA;
DROP TABLE IF EXISTS TB_ERROSLOGS;
DROP TABLE IF EXISTS TB_METODOPALPITES;
DROP TABLE IF EXISTS __EFMigrationsHistory;

-- Reativar constraints (opcional)
-- ALTER TABLE TB_PALPITES WITH CHECK CHECK CONSTRAINT ALL;
-- ALTER TABLE TB_PARTIDA_ESTAITSTICA_ESPERADAS WITH CHECK CHECK CONSTRAINT ALL;
-- ALTER TABLE TB_ESTATISTICA_ESPERADAS WITH CHECK CHECK CONSTRAINT ALL;
