// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using botAPI.Data;

#nullable disable

namespace botAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250405011657_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("botAPI.Models.Estatistica_Times", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("Bolas_Afastadas")
                        .HasColumnType("real");

                    b.Property<float>("Bolas_Afastadas_Adversaria")
                        .HasColumnType("real");

                    b.Property<float>("Bolas_Afastadas_Confrontos")
                        .HasColumnType("real");

                    b.Property<float>("Bolas_trave")
                        .HasColumnType("real");

                    b.Property<float>("Bolas_trave_Adversaria")
                        .HasColumnType("real");

                    b.Property<float>("Bolas_trave_Confrontos")
                        .HasColumnType("real");

                    b.Property<float>("Cartoes_Amarelos")
                        .HasColumnType("real");

                    b.Property<float>("Cartoes_Amarelos_Adversaria")
                        .HasColumnType("real");

                    b.Property<float>("Cartoes_Amarelos_Confrontos")
                        .HasColumnType("real");

                    b.Property<float>("Cartoes_Vermelhos")
                        .HasColumnType("real");

                    b.Property<float>("Cartoes_Vermelhos_Adversaria")
                        .HasColumnType("real");

                    b.Property<float>("Cartoes_Vermelhos_Confrontos")
                        .HasColumnType("real");

                    b.Property<string>("CasaOuFora")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<float>("Chances_Claras")
                        .HasColumnType("real");

                    b.Property<float>("Chances_Claras_Adversaria")
                        .HasColumnType("real");

                    b.Property<float>("Chances_Claras_Confrontos")
                        .HasColumnType("real");

                    b.Property<float>("Cruzamentos")
                        .HasColumnType("real");

                    b.Property<float>("Cruzamentos_Adversaria")
                        .HasColumnType("real");

                    b.Property<float>("Cruzamentos_Confrontos")
                        .HasColumnType("real");

                    b.Property<float>("Defesas_Goleiro")
                        .HasColumnType("real");

                    b.Property<float>("Defesas_Goleiro_Adversaria")
                        .HasColumnType("real");

                    b.Property<float>("Defesas_Goleiro_Confrontos")
                        .HasColumnType("real");

                    b.Property<float>("Desarmes")
                        .HasColumnType("real");

                    b.Property<float>("Desarmes_Adversaria")
                        .HasColumnType("real");

                    b.Property<float>("Desarmes_Confrontos")
                        .HasColumnType("real");

                    b.Property<float>("Escanteios")
                        .HasColumnType("real");

                    b.Property<float>("Escanteios_Adversaria")
                        .HasColumnType("real");

                    b.Property<float>("Escanteios_Confrontos")
                        .HasColumnType("real");

                    b.Property<float>("Faltas")
                        .HasColumnType("real");

                    b.Property<float>("Faltas_Adversaria")
                        .HasColumnType("real");

                    b.Property<float>("Faltas_Confrontos")
                        .HasColumnType("real");

                    b.Property<float>("Gol")
                        .HasColumnType("real");

                    b.Property<float>("GolSofrido")
                        .HasColumnType("real");

                    b.Property<float>("GolSofrido_Adversaria")
                        .HasColumnType("real");

                    b.Property<float>("GolSofrido_Confrontos")
                        .HasColumnType("real");

                    b.Property<float>("Gol_Adversaria")
                        .HasColumnType("real");

                    b.Property<float>("Gol_Confrontos")
                        .HasColumnType("real");

                    b.Property<float>("Gols_de_cabeça")
                        .HasColumnType("real");

                    b.Property<float>("Gols_de_cabeça_Adversaria")
                        .HasColumnType("real");

                    b.Property<float>("Gols_de_cabeça_Confrontos")
                        .HasColumnType("real");

                    b.Property<float>("Impedimentos")
                        .HasColumnType("real");

                    b.Property<float>("Impedimentos_Adversaria")
                        .HasColumnType("real");

                    b.Property<float>("Impedimentos_Confrontos")
                        .HasColumnType("real");

                    b.Property<float>("Interceptacoes")
                        .HasColumnType("real");

                    b.Property<float>("Interceptacoes_Adversaria")
                        .HasColumnType("real");

                    b.Property<float>("Interceptacoes_Confrontos")
                        .HasColumnType("real");

                    b.Property<float>("Laterais_Cobrados")
                        .HasColumnType("real");

                    b.Property<float>("Laterais_Cobrados_Adversaria")
                        .HasColumnType("real");

                    b.Property<float>("Laterais_Cobrados_Confrontos")
                        .HasColumnType("real");

                    b.Property<string>("NomeTime")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<float>("Passes")
                        .HasColumnType("real");

                    b.Property<float>("Passes_Adversaria")
                        .HasColumnType("real");

                    b.Property<float>("Passes_Confrontos")
                        .HasColumnType("real");

                    b.Property<float>("Passes_Totais")
                        .HasColumnType("real");

                    b.Property<float>("Passes_Totais_Adversaria")
                        .HasColumnType("real");

                    b.Property<float>("Passes_Totais_Confrontos")
                        .HasColumnType("real");

                    b.Property<float>("Passes_terco_Final")
                        .HasColumnType("real");

                    b.Property<float>("Passes_terco_Final_Adversaria")
                        .HasColumnType("real");

                    b.Property<float>("Passes_terco_Final_Confrontos")
                        .HasColumnType("real");

                    b.Property<float>("Posse_Bola")
                        .HasColumnType("real");

                    b.Property<float>("Posse_Bola_Adversaria")
                        .HasColumnType("real");

                    b.Property<float>("Posse_Bola_Confrontos")
                        .HasColumnType("real");

                    b.Property<float>("Precisao_Passes")
                        .HasColumnType("real");

                    b.Property<float>("Precisao_Passes_Adversaria")
                        .HasColumnType("real");

                    b.Property<float>("Precisao_Passes_Confrontos")
                        .HasColumnType("real");

                    b.Property<float>("Toque_Area_Adversaria")
                        .HasColumnType("real");

                    b.Property<float>("Toque_Area_Adversaria_Adversaria")
                        .HasColumnType("real");

                    b.Property<float>("Toque_Area_Confrontos_Confrontos")
                        .HasColumnType("real");

                    b.Property<float>("Total_Finalizacao")
                        .HasColumnType("real");

                    b.Property<float>("Total_Finalizacao_Adversaria")
                        .HasColumnType("real");

                    b.Property<float>("Total_Finalizacao_Confrontos")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("TB_ESTATISTICA_TIME");
                });

            modelBuilder.Entity("botAPI.Models.Palpites", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<int>("IdPartida")
                        .HasColumnType("int");

                    b.Property<double?>("Num")
                        .HasColumnType("float");

                    b.Property<int>("TipoAposta")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TB_PALPITES");
                });

            modelBuilder.Entity("botAPI.Models.Partida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Campeonato")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<DateTime>("DataPartida")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<int>("Id_EstatisticaCasa")
                        .HasColumnType("int");

                    b.Property<int>("Id_EstatisticaFora")
                        .HasColumnType("int");

                    b.Property<string>("NomeTimeCasa")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<string>("NomeTimeFora")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<bool>("PartidaAnalise")
                        .HasColumnType("bit");

                    b.Property<string>("TipoPartida")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.ToTable("TB_PARTIDAS");

                    b.HasDiscriminator().HasValue("Partida");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("botAPI.Models.Estatistica", b =>
                {
                    b.HasBaseType("botAPI.Models.Partida");

                    b.Property<int?>("Bolas_Afastadas")
                        .HasColumnType("int");

                    b.Property<int?>("Bolas_trave")
                        .HasColumnType("int");

                    b.Property<int?>("Cartoes_Amarelos")
                        .HasColumnType("int");

                    b.Property<int?>("Cartoes_Vermelhos")
                        .HasColumnType("int");

                    b.Property<string>("CasaOuFora")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<int?>("Chances_Claras")
                        .HasColumnType("int");

                    b.Property<int?>("Cruzamentos")
                        .HasColumnType("int");

                    b.Property<int?>("Defesas_Goleiro")
                        .HasColumnType("int");

                    b.Property<int?>("Desarmes")
                        .HasColumnType("int");

                    b.Property<int?>("Escanteios")
                        .HasColumnType("int");

                    b.Property<int?>("Faltas")
                        .HasColumnType("int");

                    b.Property<int?>("Gol")
                        .HasColumnType("int");

                    b.Property<int?>("GolSofrido")
                        .HasColumnType("int");

                    b.Property<int?>("Gols_de_cabeça")
                        .HasColumnType("int");

                    b.Property<int>("Id_Estatistica")
                        .HasColumnType("int");

                    b.Property<int>("Id_Partida")
                        .HasColumnType("int");

                    b.Property<int?>("Impedimentos")
                        .HasColumnType("int");

                    b.Property<int?>("Laterais_Cobrados")
                        .HasColumnType("int");

                    b.Property<string>("NomeTime")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<int?>("Passes")
                        .HasColumnType("int");

                    b.Property<int?>("Passes_Totais")
                        .HasColumnType("int");

                    b.Property<int?>("Passes_terco_Final")
                        .HasColumnType("int");

                    b.Property<int?>("Posse_Bola")
                        .HasColumnType("int");

                    b.Property<int?>("Precisao_Passes")
                        .HasColumnType("int");

                    b.Property<int?>("Toque_Area_Adversaria")
                        .HasColumnType("int");

                    b.Property<int?>("Total_Finalizacao")
                        .HasColumnType("int");

                    b.Property<int?>("interceptacoes")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Estatistica");
                });
#pragma warning restore 612, 618
        }
    }
}
