// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using botAPI.Data;

#nullable disable

namespace botAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("botAPI.Models.ErrosLogs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("OqueProvavelmenteAConteceu")
                        .HasMaxLength(510)
                        .HasColumnType("varchar(510)");

                    b.Property<string>("QualPageFoi")
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<string>("QualUrl")
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<DateTime>("horaErro")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TB_ERROSLOGS");
                });

            modelBuilder.Entity("botAPI.Models.Estatistica", b =>
                {
                    b.Property<int>("Id_Estatistica")
                        .HasColumnType("int");

                    b.Property<int?>("Bolas_Afastadas")
                        .HasColumnType("int");

                    b.Property<int?>("Bolas_Afastadas_HT")
                        .HasColumnType("int");

                    b.Property<int?>("Bolas_trave")
                        .HasColumnType("int");

                    b.Property<int?>("Bolas_trave_HT")
                        .HasColumnType("int");

                    b.Property<int?>("Cartoes_Amarelos")
                        .HasColumnType("int");

                    b.Property<int?>("Cartoes_Amarelos_HT")
                        .HasColumnType("int");

                    b.Property<int?>("Cartoes_Vermelhos")
                        .HasColumnType("int");

                    b.Property<int?>("Cartoes_Vermelhos_HT")
                        .HasColumnType("int");

                    b.Property<string>("CasaOuFora")
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<int?>("Chances_Claras")
                        .HasColumnType("int");

                    b.Property<int?>("Chances_Claras_HT")
                        .HasColumnType("int");

                    b.Property<int?>("Cruzamentos")
                        .HasColumnType("int");

                    b.Property<int?>("Cruzamentos_HT")
                        .HasColumnType("int");

                    b.Property<int?>("Defesas_Goleiro")
                        .HasColumnType("int");

                    b.Property<int?>("Defesas_Goleiro_HT")
                        .HasColumnType("int");

                    b.Property<int?>("Desarmes")
                        .HasColumnType("int");

                    b.Property<int?>("Desarmes_HT")
                        .HasColumnType("int");

                    b.Property<int?>("Escanteios")
                        .HasColumnType("int");

                    b.Property<int?>("Escanteios_HT")
                        .HasColumnType("int");

                    b.Property<int?>("Faltas")
                        .HasColumnType("int");

                    b.Property<int?>("Faltas_HT")
                        .HasColumnType("int");

                    b.Property<int?>("Gol")
                        .HasColumnType("int");

                    b.Property<int?>("GolSofrido")
                        .HasColumnType("int");

                    b.Property<int?>("GolSofrido_HT")
                        .HasColumnType("int");

                    b.Property<int?>("Gol_HT")
                        .HasColumnType("int");

                    b.Property<int?>("Gols_de_cabeça")
                        .HasColumnType("int");

                    b.Property<int?>("Gols_de_cabeça_HT")
                        .HasColumnType("int");

                    b.Property<int>("Id_Partida")
                        .HasColumnType("int");

                    b.Property<int?>("Impedimentos")
                        .HasColumnType("int");

                    b.Property<int?>("Impedimentos_HT")
                        .HasColumnType("int");

                    b.Property<int?>("Interceptacoes")
                        .HasColumnType("int");

                    b.Property<int?>("Interceptacoes_HT")
                        .HasColumnType("int");

                    b.Property<int?>("Laterais_Cobrados")
                        .HasColumnType("int");

                    b.Property<int?>("Laterais_Cobrados_HT")
                        .HasColumnType("int");

                    b.Property<string>("NomeTime")
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<string>("NomeTimeRival")
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<int?>("Passes")
                        .HasColumnType("int");

                    b.Property<int?>("Passes_HT")
                        .HasColumnType("int");

                    b.Property<int?>("Passes_Totais")
                        .HasColumnType("int");

                    b.Property<int?>("Passes_Totais_HT")
                        .HasColumnType("int");

                    b.Property<int?>("Passes_terco_Final")
                        .HasColumnType("int");

                    b.Property<int?>("Passes_terco_Final_HT")
                        .HasColumnType("int");

                    b.Property<int?>("Posse_Bola")
                        .HasColumnType("int");

                    b.Property<int?>("Posse_Bola_HT")
                        .HasColumnType("int");

                    b.Property<int?>("Precisao_Passes")
                        .HasColumnType("int");

                    b.Property<int?>("Precisao_Passes_HT")
                        .HasColumnType("int");

                    b.Property<string>("TipoPartida")
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<int?>("Toque_Area_Adversaria")
                        .HasColumnType("int");

                    b.Property<int?>("Toque_Area_Adversaria_HT")
                        .HasColumnType("int");

                    b.Property<int?>("Total_Finalizacao")
                        .HasColumnType("int");

                    b.Property<int?>("Total_Finalizacao_HT")
                        .HasColumnType("int");

                    b.HasKey("Id_Estatistica");

                    b.ToTable("TB_ESTATISTICA");
                });

            modelBuilder.Entity("botAPI.Models.Estatistica_BaseModel", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<float?>("Bolas_Afastadas")
                        .HasColumnType("real");

                    b.Property<float?>("Bolas_trave")
                        .HasColumnType("real");

                    b.Property<float?>("Cartoes_Amarelos")
                        .HasColumnType("real");

                    b.Property<float?>("Cartoes_Amarelos_DP")
                        .HasColumnType("real");

                    b.Property<float?>("Cartoes_Amarelos_Slope")
                        .HasColumnType("real");

                    b.Property<float?>("Cartoes_Vermelhos")
                        .HasColumnType("real");

                    b.Property<float?>("Cartoes_Vermelhos_DP")
                        .HasColumnType("real");

                    b.Property<float?>("Cartoes_Vermelhos_Slope")
                        .HasColumnType("real");

                    b.Property<float?>("Chances_Claras")
                        .HasColumnType("real");

                    b.Property<float?>("Cruzamentos")
                        .HasColumnType("real");

                    b.Property<float?>("Defesas_Goleiro")
                        .HasColumnType("real");

                    b.Property<float?>("Desarmes")
                        .HasColumnType("real");

                    b.Property<float?>("Desarmes_DP")
                        .HasColumnType("real");

                    b.Property<float?>("Desarmes_Slope")
                        .HasColumnType("real");

                    b.Property<float?>("Escanteios")
                        .HasColumnType("real");

                    b.Property<float?>("Escanteios_DP")
                        .HasColumnType("real");

                    b.Property<float?>("Escanteios_Slope")
                        .HasColumnType("real");

                    b.Property<float?>("Faltas")
                        .HasColumnType("real");

                    b.Property<float?>("Faltas_DP")
                        .HasColumnType("real");

                    b.Property<float?>("Faltas_Slope")
                        .HasColumnType("real");

                    b.Property<float?>("Gol")
                        .HasColumnType("real");

                    b.Property<float?>("GolSofrido")
                        .HasColumnType("real");

                    b.Property<float?>("GolSofrido_DP")
                        .HasColumnType("real");

                    b.Property<float?>("GolSofrido_Slope")
                        .HasColumnType("real");

                    b.Property<float?>("Gol_DP")
                        .HasColumnType("real");

                    b.Property<float?>("Gol_Slope")
                        .HasColumnType("real");

                    b.Property<float?>("Gols_de_cabeca")
                        .HasColumnType("real");

                    b.Property<float?>("Impedimentos")
                        .HasColumnType("real");

                    b.Property<float?>("Impedimentos_DP")
                        .HasColumnType("real");

                    b.Property<float?>("Impedimentos_Slope")
                        .HasColumnType("real");

                    b.Property<float?>("Interceptacoes")
                        .HasColumnType("real");

                    b.Property<float?>("Laterais_Cobrados")
                        .HasColumnType("real");

                    b.Property<float?>("Passes")
                        .HasColumnType("real");

                    b.Property<float?>("Passes_Totais")
                        .HasColumnType("real");

                    b.Property<float?>("Passes_terco_Final")
                        .HasColumnType("real");

                    b.Property<float?>("Posse_Bola")
                        .HasColumnType("real");

                    b.Property<float?>("Posse_Bola_DP")
                        .HasColumnType("real");

                    b.Property<float?>("Posse_Bola_Slope")
                        .HasColumnType("real");

                    b.Property<float?>("Precisao_Passes")
                        .HasColumnType("real");

                    b.Property<float?>("Toque_Area_Adversaria")
                        .HasColumnType("real");

                    b.Property<float?>("Total_Finalizacao")
                        .HasColumnType("real");

                    b.Property<float?>("Total_Finalizacao_DP")
                        .HasColumnType("real");

                    b.Property<float?>("Total_Finalizacao_Slope")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("TB_ESTATISTICA_BASEMODEL");
                });

            modelBuilder.Entity("botAPI.Models.Estatistica_Esperadas", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int?>("FTId")
                        .HasColumnType("int");

                    b.Property<int?>("FT_AdversarioId")
                        .HasColumnType("int");

                    b.Property<int>("FT_Adversario_Id")
                        .HasColumnType("int");

                    b.Property<int?>("FT_ConfrontoId")
                        .HasColumnType("int");

                    b.Property<int>("FT_Confronto_Id")
                        .HasColumnType("int");

                    b.Property<int>("FT_Id")
                        .HasColumnType("int");

                    b.Property<int?>("HTId")
                        .HasColumnType("int");

                    b.Property<int?>("HT_AdversarioId")
                        .HasColumnType("int");

                    b.Property<int>("HT_Adversario_Id")
                        .HasColumnType("int");

                    b.Property<int?>("HT_ConfrontoId")
                        .HasColumnType("int");

                    b.Property<int>("HT_Confronto_Id")
                        .HasColumnType("int");

                    b.Property<int>("HT_Id")
                        .HasColumnType("int");

                    b.Property<string>("NomeTime")
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.HasIndex("FTId");

                    b.HasIndex("FT_AdversarioId");

                    b.HasIndex("FT_ConfrontoId");

                    b.HasIndex("HTId");

                    b.HasIndex("HT_AdversarioId");

                    b.HasIndex("HT_ConfrontoId");

                    b.ToTable("TB_ESTATISTICA_ESPERADAS");
                });

            modelBuilder.Entity("botAPI.Models.Estatistica_Times", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<float?>("Bolas_Afastadas")
                        .HasColumnType("real");

                    b.Property<float?>("Bolas_Afastadas_Adversaria")
                        .HasColumnType("real");

                    b.Property<float?>("Bolas_Afastadas_Adversaria_HT")
                        .HasColumnType("real");

                    b.Property<float?>("Bolas_Afastadas_Confrontos")
                        .HasColumnType("real");

                    b.Property<float?>("Bolas_Afastadas_Confrontos_HT")
                        .HasColumnType("real");

                    b.Property<float?>("Bolas_Afastadas_HT")
                        .HasColumnType("real");

                    b.Property<float?>("Bolas_trave")
                        .HasColumnType("real");

                    b.Property<float?>("Bolas_trave_Adversaria")
                        .HasColumnType("real");

                    b.Property<float?>("Bolas_trave_Adversaria_HT")
                        .HasColumnType("real");

                    b.Property<float?>("Bolas_trave_Confrontos")
                        .HasColumnType("real");

                    b.Property<float?>("Bolas_trave_Confrontos_HT")
                        .HasColumnType("real");

                    b.Property<float?>("Bolas_trave_HT")
                        .HasColumnType("real");

                    b.Property<float?>("Cartoes_Amarelos")
                        .HasColumnType("real");

                    b.Property<float?>("Cartoes_Amarelos_Adversaria")
                        .HasColumnType("real");

                    b.Property<float?>("Cartoes_Amarelos_Adversaria_HT")
                        .HasColumnType("real");

                    b.Property<float?>("Cartoes_Amarelos_Confrontos")
                        .HasColumnType("real");

                    b.Property<float?>("Cartoes_Amarelos_Confrontos_HT")
                        .HasColumnType("real");

                    b.Property<float?>("Cartoes_Amarelos_HT")
                        .HasColumnType("real");

                    b.Property<float?>("Cartoes_Vermelhos")
                        .HasColumnType("real");

                    b.Property<float?>("Cartoes_Vermelhos_Adversaria")
                        .HasColumnType("real");

                    b.Property<float?>("Cartoes_Vermelhos_Adversaria_HT")
                        .HasColumnType("real");

                    b.Property<float?>("Cartoes_Vermelhos_Confrontos")
                        .HasColumnType("real");

                    b.Property<float?>("Cartoes_Vermelhos_Confrontos_HT")
                        .HasColumnType("real");

                    b.Property<float?>("Cartoes_Vermelhos_HT")
                        .HasColumnType("real");

                    b.Property<string>("CasaOuFora")
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<float?>("Chances_Claras")
                        .HasColumnType("real");

                    b.Property<float?>("Chances_Claras_Adversaria")
                        .HasColumnType("real");

                    b.Property<float?>("Chances_Claras_Adversaria_HT")
                        .HasColumnType("real");

                    b.Property<float?>("Chances_Claras_Confrontos")
                        .HasColumnType("real");

                    b.Property<float?>("Chances_Claras_Confrontos_HT")
                        .HasColumnType("real");

                    b.Property<float?>("Chances_Claras_HT")
                        .HasColumnType("real");

                    b.Property<float?>("Cruzamentos")
                        .HasColumnType("real");

                    b.Property<float?>("Cruzamentos_Adversaria")
                        .HasColumnType("real");

                    b.Property<float?>("Cruzamentos_Adversaria_HT")
                        .HasColumnType("real");

                    b.Property<float?>("Cruzamentos_Confrontos")
                        .HasColumnType("real");

                    b.Property<float?>("Cruzamentos_Confrontos_HT")
                        .HasColumnType("real");

                    b.Property<float?>("Cruzamentos_HT")
                        .HasColumnType("real");

                    b.Property<float?>("Defesas_Goleiro")
                        .HasColumnType("real");

                    b.Property<float?>("Defesas_Goleiro_Adversaria")
                        .HasColumnType("real");

                    b.Property<float?>("Defesas_Goleiro_Adversaria_HT")
                        .HasColumnType("real");

                    b.Property<float?>("Defesas_Goleiro_Confrontos")
                        .HasColumnType("real");

                    b.Property<float?>("Defesas_Goleiro_Confrontos_HT")
                        .HasColumnType("real");

                    b.Property<float?>("Defesas_Goleiro_HT")
                        .HasColumnType("real");

                    b.Property<float?>("Desarmes")
                        .HasColumnType("real");

                    b.Property<float?>("Desarmes_Adversaria")
                        .HasColumnType("real");

                    b.Property<float?>("Desarmes_Adversaria_HT")
                        .HasColumnType("real");

                    b.Property<float?>("Desarmes_Confrontos")
                        .HasColumnType("real");

                    b.Property<float?>("Desarmes_Confrontos_HT")
                        .HasColumnType("real");

                    b.Property<float?>("Desarmes_HT")
                        .HasColumnType("real");

                    b.Property<float?>("Escanteios")
                        .HasColumnType("real");

                    b.Property<float?>("Escanteios_Adversaria")
                        .HasColumnType("real");

                    b.Property<float?>("Escanteios_Adversaria_HT")
                        .HasColumnType("real");

                    b.Property<float?>("Escanteios_Confrontos")
                        .HasColumnType("real");

                    b.Property<float?>("Escanteios_Confrontos_HT")
                        .HasColumnType("real");

                    b.Property<float?>("Escanteios_HT")
                        .HasColumnType("real");

                    b.Property<float?>("Faltas")
                        .HasColumnType("real");

                    b.Property<float?>("Faltas_Adversaria")
                        .HasColumnType("real");

                    b.Property<float?>("Faltas_Adversaria_HT")
                        .HasColumnType("real");

                    b.Property<float?>("Faltas_Confrontos")
                        .HasColumnType("real");

                    b.Property<float?>("Faltas_Confrontos_HT")
                        .HasColumnType("real");

                    b.Property<float?>("Faltas_HT")
                        .HasColumnType("real");

                    b.Property<float?>("Gol")
                        .HasColumnType("real");

                    b.Property<float?>("GolSofrido")
                        .HasColumnType("real");

                    b.Property<float?>("GolSofrido_Adversaria")
                        .HasColumnType("real");

                    b.Property<float?>("GolSofrido_Adversaria_HT")
                        .HasColumnType("real");

                    b.Property<float?>("GolSofrido_Confrontos")
                        .HasColumnType("real");

                    b.Property<float?>("GolSofrido_Confrontos_HT")
                        .HasColumnType("real");

                    b.Property<float?>("GolSofrido_HT")
                        .HasColumnType("real");

                    b.Property<float?>("Gol_Adversaria")
                        .HasColumnType("real");

                    b.Property<float?>("Gol_Adversaria_HT")
                        .HasColumnType("real");

                    b.Property<float?>("Gol_Confrontos")
                        .HasColumnType("real");

                    b.Property<float?>("Gol_Confrontos_HT")
                        .HasColumnType("real");

                    b.Property<float?>("Gol_HT")
                        .HasColumnType("real");

                    b.Property<float?>("Gols_de_cabeça")
                        .HasColumnType("real");

                    b.Property<float?>("Gols_de_cabeça_Adversaria")
                        .HasColumnType("real");

                    b.Property<float?>("Gols_de_cabeça_Adversaria_HT")
                        .HasColumnType("real");

                    b.Property<float?>("Gols_de_cabeça_Confrontos")
                        .HasColumnType("real");

                    b.Property<float?>("Gols_de_cabeça_Confrontos_HT")
                        .HasColumnType("real");

                    b.Property<float?>("Gols_de_cabeça_HT")
                        .HasColumnType("real");

                    b.Property<float?>("Impedimentos")
                        .HasColumnType("real");

                    b.Property<float?>("Impedimentos_Adversaria")
                        .HasColumnType("real");

                    b.Property<float?>("Impedimentos_Adversaria_HT")
                        .HasColumnType("real");

                    b.Property<float?>("Impedimentos_Confrontos")
                        .HasColumnType("real");

                    b.Property<float?>("Impedimentos_Confrontos_HT")
                        .HasColumnType("real");

                    b.Property<float?>("Impedimentos_HT")
                        .HasColumnType("real");

                    b.Property<float?>("Interceptacoes")
                        .HasColumnType("real");

                    b.Property<float?>("Interceptacoes_Adversaria")
                        .HasColumnType("real");

                    b.Property<float?>("Interceptacoes_Adversaria_HT")
                        .HasColumnType("real");

                    b.Property<float?>("Interceptacoes_Confrontos")
                        .HasColumnType("real");

                    b.Property<float?>("Interceptacoes_Confrontos_HT")
                        .HasColumnType("real");

                    b.Property<float?>("Interceptacoes_HT")
                        .HasColumnType("real");

                    b.Property<float?>("Laterais_Cobrados")
                        .HasColumnType("real");

                    b.Property<float?>("Laterais_Cobrados_Adversaria")
                        .HasColumnType("real");

                    b.Property<float?>("Laterais_Cobrados_Adversaria_HT")
                        .HasColumnType("real");

                    b.Property<float?>("Laterais_Cobrados_Confrontos")
                        .HasColumnType("real");

                    b.Property<float?>("Laterais_Cobrados_Confrontos_HT")
                        .HasColumnType("real");

                    b.Property<float?>("Laterais_Cobrados_HT")
                        .HasColumnType("real");

                    b.Property<string>("NomeTime")
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<float?>("Passes")
                        .HasColumnType("real");

                    b.Property<float?>("Passes_Adversaria")
                        .HasColumnType("real");

                    b.Property<float?>("Passes_Adversaria_HT")
                        .HasColumnType("real");

                    b.Property<float?>("Passes_Confrontos")
                        .HasColumnType("real");

                    b.Property<float?>("Passes_Confrontos_HT")
                        .HasColumnType("real");

                    b.Property<float?>("Passes_HT")
                        .HasColumnType("real");

                    b.Property<float?>("Passes_Totais")
                        .HasColumnType("real");

                    b.Property<float?>("Passes_Totais_Adversaria")
                        .HasColumnType("real");

                    b.Property<float?>("Passes_Totais_Adversaria_HT")
                        .HasColumnType("real");

                    b.Property<float?>("Passes_Totais_Confrontos")
                        .HasColumnType("real");

                    b.Property<float?>("Passes_Totais_Confrontos_HT")
                        .HasColumnType("real");

                    b.Property<float?>("Passes_Totais_HT")
                        .HasColumnType("real");

                    b.Property<float?>("Passes_terco_Final")
                        .HasColumnType("real");

                    b.Property<float?>("Passes_terco_Final_Adversaria")
                        .HasColumnType("real");

                    b.Property<float?>("Passes_terco_Final_Adversaria_HT")
                        .HasColumnType("real");

                    b.Property<float?>("Passes_terco_Final_Confrontos")
                        .HasColumnType("real");

                    b.Property<float?>("Passes_terco_Final_Confrontos_HT")
                        .HasColumnType("real");

                    b.Property<float?>("Passes_terco_Final_HT")
                        .HasColumnType("real");

                    b.Property<float?>("Posse_Bola")
                        .HasColumnType("real");

                    b.Property<float?>("Posse_Bola_Adversaria")
                        .HasColumnType("real");

                    b.Property<float?>("Posse_Bola_Adversaria_HT")
                        .HasColumnType("real");

                    b.Property<float?>("Posse_Bola_Confrontos")
                        .HasColumnType("real");

                    b.Property<float?>("Posse_Bola_Confrontos_HT")
                        .HasColumnType("real");

                    b.Property<float?>("Posse_Bola_HT")
                        .HasColumnType("real");

                    b.Property<float?>("Precisao_Passes")
                        .HasColumnType("real");

                    b.Property<float?>("Precisao_Passes_Adversaria")
                        .HasColumnType("real");

                    b.Property<float?>("Precisao_Passes_Adversaria_HT")
                        .HasColumnType("real");

                    b.Property<float?>("Precisao_Passes_Confrontos")
                        .HasColumnType("real");

                    b.Property<float?>("Precisao_Passes_Confrontos_HT")
                        .HasColumnType("real");

                    b.Property<float?>("Precisao_Passes_HT")
                        .HasColumnType("real");

                    b.Property<float?>("Toque_Area_Adversaria")
                        .HasColumnType("real");

                    b.Property<float?>("Toque_Area_Adversaria_Adversaria")
                        .HasColumnType("real");

                    b.Property<float?>("Toque_Area_Adversaria_Adversaria_HT")
                        .HasColumnType("real");

                    b.Property<float?>("Toque_Area_Adversaria_Confrontos")
                        .HasColumnType("real");

                    b.Property<float?>("Toque_Area_Adversaria_Confrontos_HT")
                        .HasColumnType("real");

                    b.Property<float?>("Toque_Area_Adversaria_HT")
                        .HasColumnType("real");

                    b.Property<float?>("Total_Finalizacao")
                        .HasColumnType("real");

                    b.Property<float?>("Total_Finalizacao_Adversaria")
                        .HasColumnType("real");

                    b.Property<float?>("Total_Finalizacao_Adversaria_HT")
                        .HasColumnType("real");

                    b.Property<float?>("Total_Finalizacao_Confrontos")
                        .HasColumnType("real");

                    b.Property<float?>("Total_Finalizacao_Confrontos_HT")
                        .HasColumnType("real");

                    b.Property<float?>("Total_Finalizacao_HT")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("TB_ESTATISTICA_TIME");
                });

            modelBuilder.Entity("botAPI.Models.MetodoGeradorPalpites", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Condicoes")
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<string>("Descricao")
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<string>("Nome")
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<string>("Versao")
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.ToTable("TB_METODOPALPITES");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Condicoes = "media de gols feitos casa mais media de gols sofridos fora /2  o mesmo para visitante",
                            Descricao = "Para partidas que houver menos de 4 gols em tempo regulamentar",
                            Nome = "Under 4 gols",
                            Versao = "1.0"
                        },
                        new
                        {
                            Id = 2,
                            Condicoes = "media de gols feitos casa mais media de gols sofridos fora /2  o mesmo para visitante",
                            Descricao = "Para partidas que houver mais de 2 gols em tempo regulamentar",
                            Nome = "Over 2 gols",
                            Versao = "1.0"
                        },
                        new
                        {
                            Id = 3,
                            Condicoes = "baseado em 4 características para definir quem tem a maior probabilidade de vencer, sendo eles posse de bola,Precisão dos passes,gols e jogos sem sofre gol",
                            Descricao = "Para definir quem sera o vencedor da partida em termpo regulamentar",
                            Nome = "Vencedor do Encontro",
                            Versao = "1.0"
                        },
                        new
                        {
                            Id = 4,
                            Condicoes = "baseado na media de escanteios feitos e  sofridos de cada time /4 ",
                            Descricao = "Para definir a linha de over escanteios da Partida em termpo regulamentar",
                            Nome = "Over escanteios Variaveis",
                            Versao = "1.0"
                        },
                        new
                        {
                            Id = 5,
                            Condicoes = "baseado na media de escanteios feitos e  sofridos de cada time /4 ",
                            Descricao = "Para definir a linha de Under escanteios da Partida em termpo regulamentar",
                            Nome = "Under escanteios Variaveis",
                            Versao = "1.0"
                        },
                        new
                        {
                            Id = 6,
                            Condicoes = "media de gols feitos casa mais media de gols sofridos fora /2  ",
                            Descricao = "Para definir se um time faz um gol no adversario em termpo regulamentar",
                            Nome = "Over 0.5 Time",
                            Versao = "1.0"
                        });
                });

            modelBuilder.Entity("botAPI.Models.Palpites", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataPalpite")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(510)
                        .HasColumnType("varchar(510)");

                    b.Property<string>("GreenRed")
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<int>("IdPartida")
                        .HasColumnType("int");

                    b.Property<int>("MetodoGeradorPalpite_Id")
                        .HasColumnType("int");

                    b.Property<double>("Num")
                        .HasColumnType("float");

                    b.Property<float?>("ODD")
                        .HasColumnType("real");

                    b.Property<int>("TipoAposta")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MetodoGeradorPalpite_Id");

                    b.ToTable("TB_PALPITES");
                });

            modelBuilder.Entity("botAPI.Models.Partida", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Campeonato")
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<DateTime>("DataPartida")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_EstatisticaCasa")
                        .HasColumnType("int");

                    b.Property<int>("Id_EstatisticaFora")
                        .HasColumnType("int");

                    b.Property<string>("NomeTimeCasa")
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<string>("NomeTimeFora")
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<bool>("PartidaAnalise")
                        .HasColumnType("bit");

                    b.Property<string>("TipoPartida")
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<string>("Url_Partida")
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.ToTable("TB_PARTIDAS");
                });

            modelBuilder.Entity("botAPI.Models.Partida_Estatistica_Esperadas", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int?>("Estatisticas_Esperadas_CasaId")
                        .HasColumnType("int");

                    b.Property<int?>("Estatisticas_Esperadas_ForaId")
                        .HasColumnType("int");

                    b.Property<int>("Id_Estatisticas_Esperadas_Casa")
                        .HasColumnType("int");

                    b.Property<int>("Id_Estatisticas_Esperadas_Fora")
                        .HasColumnType("int");

                    b.Property<int>("Id_Partida")
                        .HasColumnType("int");

                    b.Property<int>("Id_Partida_FT")
                        .HasColumnType("int");

                    b.Property<int>("Id_Partida_FT_Confronto")
                        .HasColumnType("int");

                    b.Property<int>("Id_Partida_HT")
                        .HasColumnType("int");

                    b.Property<int>("Id_Partida_HT_Confronto")
                        .HasColumnType("int");

                    b.Property<int?>("PartidaId")
                        .HasColumnType("int");

                    b.Property<int?>("Partida_FTId")
                        .HasColumnType("int");

                    b.Property<int?>("Partida_FT_ConfrontoId")
                        .HasColumnType("int");

                    b.Property<int?>("Partida_HTId")
                        .HasColumnType("int");

                    b.Property<int?>("Partida_HT_ConfrontoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Estatisticas_Esperadas_CasaId");

                    b.HasIndex("Estatisticas_Esperadas_ForaId");

                    b.HasIndex("PartidaId");

                    b.HasIndex("Partida_FTId");

                    b.HasIndex("Partida_FT_ConfrontoId");

                    b.HasIndex("Partida_HTId");

                    b.HasIndex("Partida_HT_ConfrontoId");

                    b.ToTable("TB_PARTIDA_ESTAITSTICA_ESPERADAS");
                });

            modelBuilder.Entity("botAPI.Models.Estatistica_Esperadas", b =>
                {
                    b.HasOne("botAPI.Models.Estatistica_BaseModel", "FT")
                        .WithMany()
                        .HasForeignKey("FTId");

                    b.HasOne("botAPI.Models.Estatistica_BaseModel", "FT_Adversario")
                        .WithMany()
                        .HasForeignKey("FT_AdversarioId");

                    b.HasOne("botAPI.Models.Estatistica_BaseModel", "FT_Confronto")
                        .WithMany()
                        .HasForeignKey("FT_ConfrontoId");

                    b.HasOne("botAPI.Models.Estatistica_BaseModel", "HT")
                        .WithMany()
                        .HasForeignKey("HTId");

                    b.HasOne("botAPI.Models.Estatistica_BaseModel", "HT_Adversario")
                        .WithMany()
                        .HasForeignKey("HT_AdversarioId");

                    b.HasOne("botAPI.Models.Estatistica_BaseModel", "HT_Confronto")
                        .WithMany()
                        .HasForeignKey("HT_ConfrontoId");

                    b.Navigation("FT");

                    b.Navigation("FT_Adversario");

                    b.Navigation("FT_Confronto");

                    b.Navigation("HT");

                    b.Navigation("HT_Adversario");

                    b.Navigation("HT_Confronto");
                });

            modelBuilder.Entity("botAPI.Models.Palpites", b =>
                {
                    b.HasOne("botAPI.Models.MetodoGeradorPalpites", "MetodoGerador")
                        .WithMany()
                        .HasForeignKey("MetodoGeradorPalpite_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MetodoGerador");
                });

            modelBuilder.Entity("botAPI.Models.Partida_Estatistica_Esperadas", b =>
                {
                    b.HasOne("botAPI.Models.Estatistica_Esperadas", "Estatisticas_Esperadas_Casa")
                        .WithMany()
                        .HasForeignKey("Estatisticas_Esperadas_CasaId");

                    b.HasOne("botAPI.Models.Estatistica_Esperadas", "Estatisticas_Esperadas_Fora")
                        .WithMany()
                        .HasForeignKey("Estatisticas_Esperadas_ForaId");

                    b.HasOne("botAPI.Models.Partida", "Partida")
                        .WithMany()
                        .HasForeignKey("PartidaId");

                    b.HasOne("botAPI.Models.Estatistica_BaseModel", "Partida_FT")
                        .WithMany()
                        .HasForeignKey("Partida_FTId");

                    b.HasOne("botAPI.Models.Estatistica_BaseModel", "Partida_FT_Confronto")
                        .WithMany()
                        .HasForeignKey("Partida_FT_ConfrontoId");

                    b.HasOne("botAPI.Models.Estatistica_BaseModel", "Partida_HT")
                        .WithMany()
                        .HasForeignKey("Partida_HTId");

                    b.HasOne("botAPI.Models.Estatistica_BaseModel", "Partida_HT_Confronto")
                        .WithMany()
                        .HasForeignKey("Partida_HT_ConfrontoId");

                    b.Navigation("Estatisticas_Esperadas_Casa");

                    b.Navigation("Estatisticas_Esperadas_Fora");

                    b.Navigation("Partida");

                    b.Navigation("Partida_FT");

                    b.Navigation("Partida_FT_Confronto");

                    b.Navigation("Partida_HT");

                    b.Navigation("Partida_HT_Confronto");
                });
#pragma warning restore 612, 618
        }
    }
}
